version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fastapi_postgres
    restart: always
    ports:
      - "6969:5432"
    environment:
      POSTGRES_DB: fooddeliverydb
      POSTGRES_USER: fooddeliveryuser
      POSTGRES_PASSWORD: 2213
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
